version: '3.8'

services:
  terraform:
    image: hashicorp/terraform:latest
    container_name: terraform
    volumes:
      - ./../../:/gitradar
    working_dir: /gitradar/infra/terraform
    environment:
      - AWS_ACCESS_KEY_ID="test"
      - AWS_SECRET_ACCESS_KEY="test"
      - AWS_SESSION_TOKEN="test"
    extra_hosts:
      - "host.docker.internal:host-gateway"
