name: Deploy
run-name: Deploy to ${{ github.repository }} by @${{ github.actor }}

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - "main"

jobs:
  build-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Checkout LFS Objects
        run: git lfs checkout

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '20'

      - name: Set Up Maven
        run: sudo apt-get install -y maven

      - name: Pull Docker Images
        run: |
          docker pull hashicorp/terraform:latest
          docker pull localstack/localstack:latest

      - name: Start LocalStack
        run: |
          cd infra/localstack
          docker-compose up -d

      - name: Build Tokenizer
        run: |
          cd tokenizer
          pip install -r requirements.txt --target .
          zip -r ../tokenizer.zip *

      - name: Build Model Trainer
        run: |
          cd model_trainer
          zip -r ../model_trainer.zip *

      - name: Build Name Suggester
        run: |
          cd name_suggester
          zip -r ../name_suggester.zip *

      - name: Build Parser
        run: |
          cd parser
          mvn clean package

      - name: Build Code Metrics
        run: |
          cd code_metrics
          mvn clean package

      - name: Build Metrics Provider
        run: |
          cd metrics_provider
          mvn clean package

      - name: Build Utils
        run: |
          cd infra/utils/event_writer
          zip -r ../event_writer.zip *
          cd ../event_personalizer
          zip -r ../event_personalizer.zip *

      - name: Deploy with Terraform
        run: |
          cd infra/terraform
          docker-compose run --rm terraform init
          docker-compose run --rm terraform apply --auto-approve